# Generated by Django 6.0.1 on 2026-01-29 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_alter_emission_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='emission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
