# Generated by Django 6.0.1 on 2026-01-29 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_alter_emission_options_emission_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emission',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
